# Generated by Django 3.2.25 on 2024-03-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet_search_api', '0002_alter_favoriteshop_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteshop',
            name='shop_id',
            field=models.CharField(max_length=255),
        ),
    ]
